---
galaxy_info:
  author: WarehousePG Team
  description: Role for setting up DR site replication for WarehousePG clusters
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - database
    - postgresql
    - greenplum
    - warehousepg
    - dr
    - replication
    - ha

dependencies: []
