---
# Role metadata

galaxy_info:
  author: EDB
  description: WarehousePG Failover Role - Handles failover from primary to DR site
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
