---
# Handlers for WarehousePG DR Setup Role

- name: restart greenplum cluster
  become: yes
  become_user: gpadmin
  shell: |
    source {{ whpg_base_dir }}/greenplum_path.sh
    gpstop -ar
  delegate_to: "{{ groups['whpg_primary_coordinator'][0] }}"
  listen: "restart cluster"

- name: reload greenplum configuration
  become: yes
  become_user: gpadmin
  shell: |
    source {{ whpg_base_dir }}/greenplum_path.sh
    gpstop -u
  delegate_to: "{{ groups['whpg_primary_coordinator'][0] }}"
  listen: "reload config"
