---
galaxy_info:
  author: WarehousePG Team
  description: Ansible role for WarehousePG HA installation and configuration
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 9
  galaxy_tags:
    - database
    - postgresql
    - greenplum
    - warehousepg
    - ha

dependencies: []
